
"use strict";
const S={originalWorkbook:null,editableWorkbook:null,fileName:"",baseFileName:"",activeSheetName:"",sheetNames:[],headers:[],rows:[],raw:[],config:{projectColumn:"",dateColumn:"",weekColumn:"",autoUpdateWeek:false},changes:[],calendar:null,selectedEventRowIndex:null,currentSection:sessionStorage.getItem("activeSection")||"home"};
const D={};
document.addEventListener("DOMContentLoaded",()=>{cacheDom();bindEvents();restoreConfig();navigateTo(S.currentSection);detectFS();});
function cacheDom(){["fileInput","dropZone","currentFileName","documentStatus","pendingChangesCounter","downloadUpdatedBtn","saveOriginalBtn","openSidebarBtn","closeSidebarBtn","sidebar","sidebarOverlay","loadedFilePanel","loadedFileInfo","sheetSelect","settingsSheetSelect","sheetSummary","statTotalProjects","statWithDate","statWithoutDate","statPendingChanges","pendingDatesPanel","pendingDatesList","homePreviewSearch","settingsPreviewSearch","homePreviewTable","settingsPreviewTable","columnSearch","columnSelect","projectSearch","projectSelect","cellDetails","detailProject","detailColumn","detailCell","detailCurrentValue","editValueContainer","applyChangeBtn","changesList","undoLastChangeBtn","restoreAllChangesBtn","modifiedRowsPreview","calendar","calendarEmptyMessage","calendarProjectSearch","calendarWeekFilter","eventModal","eventModalContent","closeEventModalBtn","editEventDateBtn","projectColumnSelect","dateColumnSelect","weekColumnSelect","autoUpdateWeekCheckbox","saveSettingsBtn","settingsWarning","editorWarning","autoWeekNotice","exportProjectSearch","exportColumnSearch","exportProjectsList","exportColumnsList","selectAllProjectsBtn","clearProjectsBtn","selectAllColumnsBtn","clearColumnsBtn","downloadFilteredBtn","exportSummary","historyTable","toastContainer","previewPanelHome","previewPanelSettings"].forEach(id=>D[id]=document.getElementById(id));}
function bindEvents(){D.fileInput.onchange=e=>e.target.files?.[0]&&loadExcelFile(e.target.files[0]);D.dropZone.ondragover=e=>{e.preventDefault();D.dropZone.classList.add("dragover")};D.dropZone.ondragleave=()=>D.dropZone.classList.remove("dragover");D.dropZone.ondrop=e=>{e.preventDefault();D.dropZone.classList.remove("dragover");e.dataTransfer.files?.[0]&&loadExcelFile(e.dataTransfer.files[0])};D.openSidebarBtn.onclick=()=>openSidebar();D.closeSidebarBtn.onclick=()=>closeSidebar();D.sidebarOverlay.onclick=()=>closeSidebar();document.querySelectorAll(".nav-link").forEach(b=>b.onclick=()=>{navigateTo(b.dataset.section);closeSidebar()});D.sheetSelect.onchange=()=>requestSheetChange(D.sheetSelect.value);D.settingsSheetSelect.onchange=()=>requestSheetChange(D.settingsSheetSelect.value);D.saveSettingsBtn.onclick=saveSettings;[D.columnSearch,D.projectSearch].forEach(x=>x.oninput=renderEditorSelectors);D.columnSelect.onchange=updateCellDetails;D.projectSelect.onchange=updateCellDetails;D.applyChangeBtn.onclick=applyCellChange;D.undoLastChangeBtn.onclick=undoLastChange;D.restoreAllChangesBtn.onclick=restoreAllChanges;D.downloadUpdatedBtn.onclick=downloadUpdatedWorkbook;D.saveOriginalBtn.onclick=saveOverOriginalFile;D.calendarProjectSearch.oninput=renderCalendar;D.calendarWeekFilter.oninput=renderCalendar;D.closeEventModalBtn.onclick=()=>D.eventModal.classList.add("hidden");D.editEventDateBtn.onclick=editSelectedEventDate;D.homePreviewSearch.oninput=renderAllPreviews;D.settingsPreviewSearch.oninput=renderAllPreviews;D.exportProjectSearch.oninput=renderExportSelectors;D.exportColumnSearch.oninput=renderExportSelectors;D.selectAllProjectsBtn.onclick=()=>setExportCheckboxes("export-project",true);D.clearProjectsBtn.onclick=()=>setExportCheckboxes("export-project",false);D.selectAllColumnsBtn.onclick=()=>setExportCheckboxes("export-column",true);D.clearColumnsBtn.onclick=()=>setExportCheckboxes("export-column",false);D.downloadFilteredBtn.onclick=downloadFilteredWorkbook;document.querySelectorAll("input[name='exportMode']").forEach(r=>r.onchange=updateExportSummary);}
async function loadExcelFile(file){if(!file.name.toLowerCase().endsWith(".xlsx")){toast("Formato no compatible. Selecciona un archivo .xlsx.","error");return}try{const buf=await file.arrayBuffer();S.originalWorkbook=XLSX.read(buf,{type:"array",cellDates:true,cellNF:true,cellStyles:true});S.editableWorkbook=XLSX.read(buf,{type:"array",cellDates:true,cellNF:true,cellStyles:true});S.fileName=file.name;S.baseFileName=file.name.replace(/\.xlsx$/i,"");S.sheetNames=[...S.editableWorkbook.SheetNames];S.activeSheetName=S.sheetNames[0]||"";S.changes=[];loadActiveSheet();status("loaded");toast("Archivo cargado correctamente.","success")}catch(e){console.error(e);toast("No se ha podido leer el archivo Excel.","error")}}
function loadActiveSheet(){const ws=S.editableWorkbook.Sheets[S.activeSheetName];S.raw=XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:false});S.headers=(S.raw[0]||[]).map((h,i)=>String(h||"").trim()||`Columna ${i+1}`);S.rows=S.raw.slice(1).map((r,i)=>({rowIndex:i,excelRow:i+2,values:normRow(r,S.headers.length)}));detectColumns();renderAll()}
function normRow(r,l){r=Array.isArray(r)?r.slice(0,l):[];while(r.length<l)r.push("");return r}
function requestSheetChange(n){if(!n||n===S.activeSheetName)return;if(S.changes.length&&!confirm("Hay cambios sin descargar en la hoja actual. Si cambias de hoja, podrían perderse si no exportas. ¿Quieres continuar?")){syncSheetSelectors();return}S.activeSheetName=n;S.changes=[];loadActiveSheet();status("loaded")}
function normalizeText(t){return String(t||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[()_\-./]/g," ").replace(/\s+/g," ").trim()}
function detectColumns(){const hs=S.headers.map(normalizeText);const cand=["PROYECTO","NOMBRE PROYECTO","PROJECT","NOMBRE","OBRA","ID PROYECTO"].map(normalizeText);let p="";for(const c of cand){let i=hs.findIndex(h=>h===c);if(i<0)i=hs.findIndex(h=>h.includes(c));if(i>=0){p=S.headers[i];break}}let d="",w="";hs.forEach((h,i)=>{if(!d&&h.includes("FECHA")&&h.includes("REAL")&&h.includes("RECEPCION")&&!h.includes("WEEK")&&!h.includes("SEMANA"))d=S.headers[i];if(!w&&h.includes("RECEPCION")&&(h.includes("WEEK")||h.includes("SEMANA")))w=S.headers[i]});S.config.projectColumn=p||S.config.projectColumn||"";S.config.dateColumn=d||S.config.dateColumn||"";S.config.weekColumn=w||S.config.weekColumn||""}
function saveSettings(){S.activeSheetName=D.settingsSheetSelect.value;S.config.projectColumn=D.projectColumnSelect.value;S.config.dateColumn=D.dateColumnSelect.value;S.config.weekColumn=D.weekColumnSelect.value;S.config.autoUpdateWeek=D.autoUpdateWeekCheckbox.checked;sessionStorage.setItem("excelConfig",JSON.stringify(S.config));loadActiveSheet();toast("Configuración guardada durante la sesión.","success")}
function restoreConfig(){try{Object.assign(S.config,JSON.parse(sessionStorage.getItem("excelConfig")||"{}"))}catch{}}
function navigateTo(sec){S.currentSection=sec;sessionStorage.setItem("activeSection",sec);document.querySelectorAll(".screen").forEach(e=>e.classList.remove("active"));document.getElementById(`section-${sec}`)?.classList.add("active");document.querySelectorAll(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.section===sec));if(sec==="calendar")renderCalendar();if(sec==="export")renderExportSelectors();if(sec==="history")renderHistoryTable()}
function openSidebar(){D.sidebar.classList.add("open");D.sidebarOverlay.classList.add("visible")}function closeSidebar(){D.sidebar.classList.remove("open");D.sidebarOverlay.classList.remove("visible")}
function renderAll(){syncPanels();syncSheetSelectors();renderSettingsSelectors();renderEditorSelectors();updateCellDetails();renderAllPreviews();renderPendingDates();renderChangesPreview();renderHistoryTable();renderExportSelectors();renderCalendar();counters()}
function syncPanels(){const has=!!S.editableWorkbook;D.currentFileName.textContent=has?S.fileName:"Ningún archivo seleccionado";[D.loadedFilePanel,D.previewPanelHome,D.previewPanelSettings].forEach(e=>e.classList.toggle("hidden",!has));D.downloadUpdatedBtn.disabled=!has;if(!has)return;D.loadedFileInfo.textContent=`${S.fileName} · ${S.sheetNames.length} hoja(s)`;D.sheetSummary.innerHTML=`<strong>Hoja activa:</strong> ${esc(S.activeSheetName)}<br><strong>Columnas:</strong> ${S.headers.length}<br><strong>Filas de datos:</strong> ${S.rows.length}<br><strong>Columna proyecto:</strong> ${esc(S.config.projectColumn||"No configurada")}<br><strong>Columna fecha real recepción:</strong> ${esc(S.config.dateColumn||"No configurada")}<br><strong>Columna semana recepción:</strong> ${esc(S.config.weekColumn||"No configurada")}`;setWarn(D.settingsWarning,!S.config.projectColumn?"No hemos podido identificar automáticamente la columna de proyectos. Selecciónala manualmente en Configuración del archivo.":"");setWarn(D.editorWarning,!S.config.dateColumn?"Selecciona manualmente la columna correspondiente a FECHA REAL RECEPCIÓN.":"")}
function syncSheetSelectors(){fill(D.sheetSelect,S.sheetNames,S.activeSheetName);fill(D.settingsSheetSelect,S.sheetNames,S.activeSheetName)}
function renderSettingsSelectors(){fill(D.projectColumnSelect,S.headers,S.config.projectColumn,"Selecciona columna...");fill(D.dateColumnSelect,S.headers,S.config.dateColumn,"Selecciona columna...");fill(D.weekColumnSelect,["",...S.headers],S.config.weekColumn,"Sin columna WEEK");D.autoUpdateWeekCheckbox.checked=S.config.autoUpdateWeek}
function fill(sel,opts,val,ph=""){sel.innerHTML="";if(ph){const o=new Option(ph,"");sel.add(o)}opts.forEach(v=>{const o=new Option(v||ph,v);o.selected=v===val;sel.add(o)})}
function counters(){const di=colIdx(S.config.dateColumn),total=S.rows.length,withDate=di>=0?S.rows.filter(r=>parseDateValue(r.values[di])).length:0;D.statTotalProjects.textContent=total;D.statWithDate.textContent=withDate;D.statWithoutDate.textContent=Math.max(total-withDate,0);D.statPendingChanges.textContent=S.changes.length;D.pendingChangesCounter.textContent=`Cambios pendientes: ${S.changes.length}`}
function renderEditorSelectors(){if(!S.editableWorkbook)return;const cq=normalizeText(D.columnSearch.value),pq=normalizeText(D.projectSearch.value),sc=D.columnSelect.value,sp=D.projectSelect.value;D.columnSelect.innerHTML="";S.headers.filter(h=>normalizeText(h).includes(cq)).forEach(h=>{const o=new Option(h,h);o.selected=h===sc;D.columnSelect.add(o)});D.projectSelect.innerHTML="";S.rows.filter(r=>normalizeText(projectName(r)).includes(pq)).forEach(r=>{const o=new Option(projectName(r),String(r.rowIndex));o.selected=String(r.rowIndex)===sp;D.projectSelect.add(o)})}
function updateCellDetails(){const cn=D.columnSelect.value,ri=Number(D.projectSelect.value),ci=colIdx(cn),r=S.rows[ri];if(!cn||Number.isNaN(ri)||!r||ci<0){D.cellDetails.classList.add("hidden");return}const ref=XLSX.utils.encode_cell({r:r.excelRow-1,c:ci}),val=r.values[ci];D.detailProject.textContent=projectName(r);D.detailColumn.textContent=cn;D.detailCell.textContent=ref;D.detailCurrentValue.textContent=display(val);renderInput(cn,val);const aw=cn===S.config.dateColumn&&S.config.autoUpdateWeek&&S.config.weekColumn;D.autoWeekNotice.classList.toggle("hidden",!aw);D.autoWeekNotice.textContent=aw?"Al aplicar este cambio también se actualizará automáticamente la columna WEEK con la semana ISO correspondiente.":"";D.cellDetails.classList.remove("hidden")}
function renderInput(cn,val){D.editValueContainer.innerHTML="";let el=document.createElement("input");el.id="editValueInput";el.className="input";if(isDateCol(cn)){el.type="date";const d=parseDateValue(val);el.value=d?dateInput(d):""}else if(isNumCol(cn)){el.type="number";el.step="any";el.value=val??""}else{const u=uniqueVals(cn);if(u.length>1&&u.length<=12){el=document.createElement("select");el.id="editValueInput";el.className="input";[String(val??""),...u.filter(x=>String(x)!==String(val))].forEach(v=>el.add(new Option(v,v)))}else{el.type="text";el.value=val??""}}D.editValueContainer.appendChild(el)}
function applyCellChange(){if(!ensure())return;const cn=D.columnSelect.value,ri=Number(D.projectSelect.value),r=S.rows[ri],ci=colIdx(cn),inp=document.getElementById("editValueInput");if(!r||ci<0||!inp){toast("Error de selección o formato.","error");return}let nv=inp.value;if(isDateCol(cn)){if(nv){const d=parseDateValue(nv);if(!d){toast("Introduce una fecha válida.","error");return}nv=spanishDate(d)}else nv=""}const ov=r.values[ci];if(String(ov??"")===String(nv??"")){toast("No hay cambios que aplicar.","info");return}registerChange(ri,ci,ov,nv,"manual");if(cn===S.config.dateColumn&&S.config.autoUpdateWeek&&S.config.weekColumn){const wi=colIdx(S.config.weekColumn),d=parseDateValue(nv);if(wi>=0&&d){const w=getISOWeek(d),ow=r.values[wi];if(String(ow??"")!==String(w))registerChange(ri,wi,ow,w,"auto-week")}}status("dirty");toast("Cambio aplicado.","success");renderAll();D.columnSelect.value=cn;D.projectSelect.value=String(ri);updateCellDetails()}
function registerChange(ri,ci,ov,nv,src){const r=S.rows[ri],ref=XLSX.utils.encode_cell({r:r.excelRow-1,c:ci});S.changes.push({rowIndex:ri,columnIndex:ci,columnName:S.headers[ci],project:projectName(r),cellRef:ref,oldValue:ov,newValue:nv,timestamp:new Date().toLocaleString("es-ES"),source:src});r.values[ci]=nv;writeCell(r.excelRow,ci,nv)}
function writeCell(excelRow,ci,v){const ws=S.editableWorkbook.Sheets[S.activeSheetName],ref=XLSX.utils.encode_cell({r:excelRow-1,c:ci}),h=S.headers[ci];if(v===""){ws[ref]={t:"s",v:""};return}if(isDateCol(h)){const d=parseDateValue(v);ws[ref]=d?{t:"d",v:d,z:"dd/mm/yyyy"}:{t:"s",v:String(v)}}else if(String(v).trim()!==""&&!Number.isNaN(Number(String(v).replace(",","."))))ws[ref]={t:"n",v:Number(String(v).replace(",","."))};else ws[ref]={t:"s",v:String(v)}}
function renderChangesPreview(){D.undoLastChangeBtn.disabled=S.changes.length===0;D.restoreAllChangesBtn.disabled=S.changes.length===0;if(!S.changes.length){D.changesList.className="changes-list empty";D.changesList.textContent="No hay cambios pendientes.";D.modifiedRowsPreview.innerHTML="";return}D.changesList.className="changes-list";D.changesList.innerHTML=S.changes.slice().reverse().map(c=>`<div class="change-item"><strong>${esc(c.project)}</strong> | ${esc(c.cellRef)} | ${esc(c.columnName)}<br>${esc(display(c.oldValue))} → ${esc(display(c.newValue))}<br><small>${esc(c.timestamp)}${c.source==="auto-week"?" · Semana automática":""}</small></div>`).join("");const rows=[...new Set(S.changes.map(c=>c.rowIndex))].map(i=>S.rows[i]);const keys=new Set(S.changes.map(c=>`${c.rowIndex}-${c.columnIndex}`));D.modifiedRowsPreview.innerHTML=tableHtml(S.headers,rows,keys)}
function undoLastChange(){const c=S.changes.pop();if(!c)return;const r=S.rows[c.rowIndex];r.values[c.columnIndex]=c.oldValue;writeCell(r.excelRow,c.columnIndex,c.oldValue);toast("Cambio deshecho.","success");if(!S.changes.length)status("loaded");renderAll()}
function restoreAllChanges(){if(!S.changes.length)return;if(!confirm("¿Seguro que quieres restaurar todos los cambios realizados durante esta sesión?"))return;while(S.changes.length){const c=S.changes.pop(),r=S.rows[c.rowIndex];r.values[c.columnIndex]=c.oldValue;writeCell(r.excelRow,c.columnIndex,c.oldValue)}status("loaded");toast("Todos los cambios han sido restaurados.","success");renderAll()}
function renderHistoryTable(){if(!S.changes.length){D.historyTable.innerHTML=`<div class="empty">No hay cambios en el historial.</div>`;return}D.historyTable.innerHTML=`<table><thead><tr>${["Proyecto","Celda","Columna","Valor anterior","Valor nuevo","Fecha y hora","Origen"].map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${S.changes.map(c=>`<tr><td>${esc(c.project)}</td><td>${esc(c.cellRef)}</td><td>${esc(c.columnName)}</td><td>${esc(display(c.oldValue))}</td><td>${esc(display(c.newValue))}</td><td>${esc(c.timestamp)}</td><td>${c.source==="auto-week"?"Semana automática":"Manual"}</td></tr>`).join("")}</tbody></table>`}
function renderCalendar(){if(!S.editableWorkbook||!S.config.dateColumn)return;const events=calendarEvents();D.calendarEmptyMessage.classList.toggle("hidden",events.length>0);if(S.calendar)S.calendar.destroy();S.calendar=new FullCalendar.Calendar(D.calendar,{initialView:"dayGridMonth",locale:"es",height:"auto",headerToolbar:{left:"prev,next today",center:"title",right:"dayGridMonth,timeGridWeek"},buttonText:{today:"Hoy",month:"Mes",week:"Semana"},events,eventClick:i=>{S.selectedEventRowIndex=i.event.extendedProps.rowIndex;openEventModal(i.event)}});S.calendar.render()}
function calendarEvents(){const di=colIdx(S.config.dateColumn),wi=colIdx(S.config.weekColumn),pq=normalizeText(D.calendarProjectSearch.value),wq=normalizeText(D.calendarWeekFilter.value);if(di<0)return[];return S.rows.map(r=>{const d=parseDateValue(r.values[di]);if(!d)return null;const p=projectName(r),w=wi>=0?r.values[wi]:"";if(pq&&!normalizeText(p).includes(pq))return null;if(wq&&!normalizeText(w).includes(wq))return null;return{title:`${p} — Recepción${w?` · Semana ${w}`:""}`,start:dateInput(d),allDay:true,extendedProps:{rowIndex:r.rowIndex,project:p,week:w,dateValue:r.values[di],cellRef:XLSX.utils.encode_cell({r:r.excelRow-1,c:di})}}}).filter(Boolean)}
function openEventModal(ev){const p=ev.extendedProps;D.eventModalContent.innerHTML=`<p><strong>Nombre del proyecto:</strong> ${esc(p.project)}</p><p><strong>Fecha real de recepción:</strong> ${esc(display(p.dateValue))}</p><p><strong>Semana:</strong> ${esc(p.week||"No indicada")}</p><p><strong>Celda Excel:</strong> ${esc(p.cellRef)}</p>`;D.eventModal.classList.remove("hidden")}
function editSelectedEventDate(){if(S.selectedEventRowIndex==null)return;D.eventModal.classList.add("hidden");navigateTo("editor");D.columnSelect.value=S.config.dateColumn;D.projectSelect.value=String(S.selectedEventRowIndex);updateCellDetails()}
function renderExportSelectors(){if(!S.editableWorkbook)return;const pq=normalizeText(D.exportProjectSearch.value),cq=normalizeText(D.exportColumnSearch.value),cp=checked("export-project"),cc=checked("export-column");D.exportProjectsList.innerHTML="";S.rows.filter(r=>normalizeText(projectName(r)).includes(pq)).forEach(r=>D.exportProjectsList.appendChild(chk("export-project",String(r.rowIndex),projectName(r),cp.includes(String(r.rowIndex)))));D.exportColumnsList.innerHTML="";S.headers.filter(h=>normalizeText(h).includes(cq)).forEach(h=>D.exportColumnsList.appendChild(chk("export-column",h,h,cc.includes(h))));updateExportSummary()}
function chk(name,value,label,checked){const w=document.createElement("label");w.className="checkbox-row";const i=document.createElement("input");i.type="checkbox";i.name=name;i.value=value;i.checked=checked;i.onchange=updateExportSummary;w.append(i,document.createTextNode(" "+label));return w}
function checked(name){return[...document.querySelectorAll(`input[name='${name}']:checked`)].map(x=>x.value)}function setExportCheckboxes(n,v){document.querySelectorAll(`input[name='${n}']`).forEach(c=>c.checked=v);updateExportSummary()}function exportMode(){return document.querySelector("input[name='exportMode']:checked")?.value||"selectedColumns"}
function updateExportSummary(){const ps=checked("export-project"),cs=checked("export-column"),m=exportMode(),fn=`${S.baseFileName||"archivo"}_FILTRADO_${today()}.xlsx`;D.exportSummary.innerHTML=`<strong>Resumen previo:</strong><br>Proyectos seleccionados: ${ps.length}<br>Columnas seleccionadas: ${m==="allColumns"?"Todas":cs.length}<br>Modo: ${m==="allColumns"?"Todas las columnas de los proyectos seleccionados":"Solo proyectos y columnas seleccionados"}<br>Nombre del archivo: ${esc(fn)}`}
function downloadFilteredWorkbook(){if(!ensure())return;const ps=checked("export-project").map(Number),cs=checked("export-column"),m=exportMode();if(!ps.length){toast("Si no se ha seleccionado ningún proyecto, no se puede descargar.","error");return}if(m==="selectedColumns"&&!cs.length){toast("Selecciona al menos una columna para exportar.","error");return}const idx=m==="allColumns"?S.headers.map((_,i)=>i):cs.map(colIdx).filter(i=>i>=0),aoa=[idx.map(i=>S.headers[i]),...ps.map(r=>idx.map(i=>S.rows[r].values[i]))],wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(aoa),"Proyectos Filtrados");XLSX.writeFile(wb,`${S.baseFileName}_FILTRADO_${today()}.xlsx`);status("saved");toast("Excel filtrado descargado.","success")}
function downloadUpdatedWorkbook(){if(!ensure())return;XLSX.writeFile(S.editableWorkbook,`${S.baseFileName}_ACTUALIZADO_${today()}.xlsx`);S.changes=[];status("saved");renderAll();toast("Copia actualizada descargada.","success")}
function detectFS(){if("showSaveFilePicker" in window)D.saveOriginalBtn.classList.remove("hidden")}
async function saveOverOriginalFile(){if(!ensure())return;if(!confirm("Advertencia: esta acción puede modificar el archivo seleccionado si el navegador lo permite. Asegúrate de tener una copia de seguridad. ¿Quieres continuar?"))return;try{const h=await window.showSaveFilePicker({suggestedName:S.fileName,types:[{description:"Excel .xlsx",accept:{"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":[".xlsx"]}}]}),data=XLSX.write(S.editableWorkbook,{bookType:"xlsx",type:"array"}),w=await h.createWritable();await w.write(data);await w.close();S.changes=[];status("saved");renderAll();toast("Archivo guardado correctamente.","success")}catch(e){console.error(e);toast("No se ha podido guardar sobre el archivo.","error")}}
function renderAllPreviews(){if(!S.editableWorkbook)return;D.homePreviewTable.innerHTML=preview(D.homePreviewSearch.value);D.settingsPreviewTable.innerHTML=preview(D.settingsPreviewSearch.value)}function preview(q){const nq=normalizeText(q),keys=new Set(S.changes.map(c=>`${c.rowIndex}-${c.columnIndex}`)),rows=S.rows.filter(r=>!nq||normalizeText(projectName(r)).includes(nq)).slice(0,20);return tableHtml(S.headers,rows,keys)}
function tableHtml(headers,rows,keys=new Set()){if(!headers.length)return`<div class="empty">No hay datos para mostrar.</div>`;return`<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${headers.map((_,i)=>`<td class="${keys.has(`${r.rowIndex}-${i}`)?"changed-cell":""}">${esc(display(r.values[i]))}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function renderPendingDates(){const di=colIdx(S.config.dateColumn);if(!S.editableWorkbook||di<0){D.pendingDatesPanel.classList.add("hidden");return}const rows=S.rows.filter(r=>!parseDateValue(r.values[di]));D.pendingDatesPanel.classList.remove("hidden");if(!rows.length){D.pendingDatesList.innerHTML=`<div class="empty">No hay proyectos pendientes de fecha de recepción.</div>`;return}D.pendingDatesList.innerHTML="";rows.forEach(r=>{const e=document.createElement("div");e.className="project-item";e.textContent=projectName(r);e.onclick=()=>{navigateTo("editor");D.columnSelect.value=S.config.dateColumn;D.projectSelect.value=String(r.rowIndex);updateCellDetails()};D.pendingDatesList.appendChild(e)})}
function colIdx(c){return S.headers.findIndex(h=>h===c)}function projectName(r){const i=colIdx(S.config.projectColumn);return String(i>=0?r.values[i]||`Fila ${r.excelRow}`:`Fila ${r.excelRow}`)}function isDateCol(c){const n=normalizeText(c);return c===S.config.dateColumn||n.includes("FECHA")||n.includes("DATE")}function isNumCol(c){const i=colIdx(c),s=S.rows.map(r=>r.values[i]).filter(v=>String(v).trim()!=="").slice(0,20);return s.length>0&&s.every(v=>!Number.isNaN(Number(String(v).replace(",","."))))}function uniqueVals(c){const i=colIdx(c);return[...new Set(S.rows.map(r=>r.values[i]).filter(v=>String(v).trim()!=="").map(String))]}
function parseDateValue(v){if(!v)return null;if(v instanceof Date&&!Number.isNaN(v.getTime()))return v;if(typeof v==="number"){const p=XLSX.SSF.parse_date_code(v);return p?new Date(p.y,p.m-1,p.d):null}const t=String(v).trim(),iso=t.match(/^(\d{4})-(\d{2})-(\d{2})$/),es=t.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})$/);if(iso)return validDate(+iso[1],+iso[2]-1,+iso[3]);if(es){let y=+es[3];if(y<100)y+=2000;return validDate(y,+es[2]-1,+es[1])}const d=new Date(t);return Number.isNaN(d.getTime())?null:d}function validDate(y,m,d){const x=new Date(y,m,d);return x.getFullYear()===y&&x.getMonth()===m&&x.getDate()===d?x:null}function dateInput(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function spanishDate(d){return`${String(d.getDate()).padStart(2,"0")}/${String(d.getMonth()+1).padStart(2,"0")}/${d.getFullYear()}`}function getISOWeek(d){const u=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const day=u.getUTCDay()||7;u.setUTCDate(u.getUTCDate()+4-day);const ys=new Date(Date.UTC(u.getUTCFullYear(),0,1));return Math.ceil((((u-ys)/86400000)+1)/7)}function display(v){return v instanceof Date?spanishDate(v):(v==null?"":String(v))}function today(){return dateInput(new Date())}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function ensure(){if(!S.editableWorkbook){toast("Primero debes seleccionar un archivo Excel.","error");return false}return true}
function status(st){D.documentStatus.classList.remove("neutral","loaded","dirty","saved");const map={loaded:["Archivo cargado","loaded"],dirty:["Cambios sin guardar","dirty"],saved:["Copia descargada correctamente","saved"],neutral:["Sin archivo cargado","neutral"]};const m=map[st]||map.neutral;D.documentStatus.textContent=m[0];D.documentStatus.classList.add(m[1]);counters()}function toast(msg,type="info"){const t=document.createElement("div");t.className=`toast ${type}`;t.textContent=msg;D.toastContainer.appendChild(t);setTimeout(()=>t.remove(),4200)}function setWarn(el,msg){if(!el)return;el.textContent=msg;el.classList.toggle("hidden",!msg)}
